name: CI

on: [push]

defaults:
    run:
        shell: bash

jobs:
    build_ubuntu:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: update
              run: sudo apt update

            - name: build project
              run: docker-compose build